<?php

namespace App\Services\Ocr;

use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Validation\ValidationException;

/**
 * Reassembles browser-sliced uploads.
 *
 * PHP's `upload_max_filesize` is 40M here, but model weights are around 1.3 GB and
 * a dataset can be thousands of images. A plain multipart post is rejected by PHP
 * before Laravel ever sees it, so chunked upload is a requirement rather than an
 * optimisation: the browser slices each file, posts the pieces, and this class
 * stitches them back together before the result is handed to the OCR service.
 *
 * Layout under storage/app/ocr-uploads/:
 *
 *     <user id>/<upload id>/parts/<file key>/data            the file being accumulated
 *     <user id>/<upload id>/parts/<file key>/.progress.json  how much of it is durable
 *     <user id>/<upload id>/parts/<file key>/<index>.part    slices that arrived early
 *     <user id>/<upload id>/files/<relative path>            assembled files
 *     <user id>/<upload id>/completed/<file key>.json        completion marker
 *
 * Slices are appended to `data` as they arrive rather than each being kept and
 * concatenated at the end. The browser awaits each POST, so they arrive in order and
 * the finished file needs no second pass: committing it is a rename. A 1.3 GB model
 * therefore crosses the disk once here instead of twice, and there is no multi-minute
 * stall after the last slice while the pieces are stitched together.
 *
 * Namespacing by user id is deliberate: an upload id is generated by the browser,
 * so one account must not be able to guess another's and claim its files.
 */
class ChunkedUpload
{
    /** Ids are browser-generated, so they are validated rather than trusted. */
    private const ID_PATTERN = '/^[A-Za-z0-9]{8,64}$/';

    /** A 1.3 GB file at 5 MB a slice is ~270 chunks. 100 GB at 32 MB is ~3 200
     *  chunks. This gives generous headroom for either. */
    private const MAX_CHUNKS = 10_000;

    /** Name of the file each slice is appended to. Deliberately not '*.part', which
     *  is the glob used to find slices that arrived out of order. */
    private const ACCUMULATOR = 'data';

    /** Records how many leading slices are durably in the accumulator. */
    private const PROGRESS = '.progress.json';

    /**
     * Room left under PHP's body limit for everything in a chunk request that is not
     * the chunk itself: the six form fields, the multipart boundaries and the part
     * headers. A few hundred bytes in practice; 1 MB means a long relative path can
     * never tip a request over the limit.
     */
    private const MULTIPART_HEADROOM = 1_048_576;

    /**
     * Chunk size bounds. Below 1 MB a 1.3 GB model needs more than MAX_CHUNKS
     * requests; above 32 MB the saving over 32 MB is slight, while a stalled slice
     * costs more to resend.
     */
    private const MIN_CHUNK_BYTES = 1_048_576;

    private const MAX_CHUNK_BYTES = 33_554_432;

    /** Abandoned uploads are swept after this long. */
    private const STALE_HOURS = 24;

    /**
     * Extensions accepted in any assembled file. The OCR service applies its own
     * whitelist too - this is the outer of two gates, not the only one.
     */
    private const ALLOWED_EXTENSIONS = [
        // Model folders
        'json', 'safetensors', 'bin', 'txt', 'model',
        // Datasets
        'zip', 'csv',
        // Predict images
        'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff',
    ];

    /**
     * Store one slice. When the last one arrives, assemble the file.
     *
     * @return array{complete: bool, received: int, total: int, name: string, relative_path: string, path: string|null}
     */
    public function receive(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $filename,
        int $index,
        int $total,
        UploadedFile $chunk,
        ?string $relativePath = null,
    ): array {
        $uploadId = $this->safeId($uploadId, 'upload_id');
        $fileKey = $this->safeId($fileKey, 'file_key');
        $relativePath = $relativePath === null
            ? $this->safeFilename($filename)
            : $this->safeRelativePath($relativePath, $filename);
        $name = basename($relativePath);

        if ($total < 1 || $total > self::MAX_CHUNKS) {
            throw ValidationException::withMessages([
                'total' => 'Chunk count must be between 1 and '.self::MAX_CHUNKS.'.',
            ]);
        }

        if ($index < 0 || $index >= $total) {
            throw ValidationException::withMessages([
                'index' => 'Chunk index is outside the declared range.',
            ]);
        }

        $completed = $this->completedTarget($actor, $uploadId, $fileKey, $relativePath);
        if ($completed !== null && $index === $total - 1) {
            $this->deleteDirectory($this->partsDirectory($actor, $uploadId, $fileKey));

            return [
                'complete' => true,
                'received' => $total,
                'total' => $total,
                'name' => $name,
                'relative_path' => $relativePath,
                'path' => $completed,
            ];
        }

        $partsDir = $this->partsDirectory($actor, $uploadId, $fileKey);
        $this->ensureDirectory($partsDir);

        [$absorbed, $parked] = $this->absorb($partsDir, $index, $chunk);

        if ($absorbed < $total) {
            return [
                'complete' => false,
                'received' => min($absorbed + $parked, $total),
                'total' => $total,
                'name' => $name,
                'relative_path' => $relativePath,
                'path' => null,
            ];
        }

        return [
            'complete' => true,
            'received' => $total,
            'total' => $total,
            'name' => $name,
            'relative_path' => $relativePath,
            'path' => $this->commit(
                $actor,
                $uploadId,
                $fileKey,
                $relativePath,
            ),
        ];
    }

    /**
     * Fold one slice into the file being accumulated for this file key.
     *
     * The browser awaits each POST, so the ordinary case is a plain append and the
     * upload is finished the moment the last slice lands. A slice that arrives early
     * is parked as <index>.part and folded in as soon as the gap ahead of it is
     * filled, so a retry or a client that does not send strictly in order still
     * works. A slice already absorbed is dropped: resending it must not duplicate
     * bytes.
     *
     * @return array{0: int, 1: int} leading slices absorbed, slices still parked
     */
    private function absorb(string $partsDir, int $index, UploadedFile $chunk): array
    {
        $accumulator = $partsDir.DIRECTORY_SEPARATOR.self::ACCUMULATOR;
        $handle = @fopen($accumulator, 'c+b');

        if ($handle === false) {
            throw new OcrServiceException('Could not open the upload for writing.');
        }

        if (! flock($handle, LOCK_EX)) {
            fclose($handle);

            throw new OcrServiceException('Could not lock the upload for writing.');
        }

        try {
            $progress = $this->readProgress($partsDir);

            // Back to the last byte count recorded as durable. A slice whose request
            // died midway through its append would otherwise be counted twice.
            if (! ftruncate($handle, $progress['bytes']) || fseek($handle, 0, SEEK_END) !== 0) {
                throw new OcrServiceException('Could not rewind a partial slice.');
            }

            if ($index > $progress['count']) {
                // Ahead of the gap: keep it until the slices before it arrive.
                $chunk->move($partsDir, $index.'.part');
            } elseif ($index === $progress['count']) {
                $source = $chunk->getRealPath();
                $parked = false;

                do {
                    $this->append($handle, $source, $progress['count']);

                    if ($parked) {
                        @unlink($source);
                    }

                    $progress['count']++;
                    $progress['bytes'] = ftell($handle);
                    $this->writeProgress($partsDir, $progress);

                    $source = $partsDir.DIRECTORY_SEPARATOR.$progress['count'].'.part';
                    $parked = true;
                } while (is_file($source));
            }

            return [
                $progress['count'],
                count(glob($partsDir.DIRECTORY_SEPARATOR.'*.part') ?: []),
            ];
        } finally {
            flock($handle, LOCK_UN);
            fclose($handle);
        }
    }

    /**
     * Copy one slice onto the end of the accumulator.
     *
     * Streamed: reading a 32 MB slice into a string is affordable, but doing it for a
     * whole 1.3 GB file is not, and this is the only place the size of the upload
     * touches memory.
     *
     * @param  resource  $handle
     */
    private function append($handle, string $path, int $index): void
    {
        $in = @fopen($path, 'rb');

        if ($in === false) {
            throw new OcrServiceException("Chunk {$index} could not be read. Retry the upload.");
        }

        $copied = stream_copy_to_stream($in, $handle);
        fclose($in);

        if ($copied === false || ! fflush($handle)) {
            throw new OcrServiceException("Chunk {$index} could not be written. Retry the upload.");
        }
    }

    /**
     * @return array{count: int, bytes: int}
     */
    private function readProgress(string $partsDir): array
    {
        $path = $partsDir.DIRECTORY_SEPARATOR.self::PROGRESS;

        if (! is_file($path)) {
            return ['count' => 0, 'bytes' => 0];
        }

        $data = json_decode((string) @file_get_contents($path), true);

        if (! is_array($data) || ! isset($data['count'], $data['bytes'])) {
            // Restarting from zero here would silently duplicate or drop bytes, so
            // this fails loudly instead.
            throw new OcrServiceException('The upload progress record is unreadable. Retry the upload.');
        }

        return ['count' => (int) $data['count'], 'bytes' => (int) $data['bytes']];
    }

    /**
     * @param  array{count: int, bytes: int}  $progress
     */
    private function writeProgress(string $partsDir, array $progress): void
    {
        $written = @file_put_contents(
            $partsDir.DIRECTORY_SEPARATOR.self::PROGRESS,
            (string) json_encode($progress),
            LOCK_EX,
        );

        if ($written === false) {
            throw new OcrServiceException('Could not record upload progress.');
        }
    }

    /**
     * Move the completed accumulator into place under files/.
     *
     * Nothing is copied: the accumulator already holds every slice in order and sits
     * on the same volume as its target, so committing it is a rename.
     */
    private function commit(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $relativePath,
    ): string {
        $target = $this->filesDirectory($actor, $uploadId)
            .DIRECTORY_SEPARATOR.str_replace('/', DIRECTORY_SEPARATOR, $relativePath);
        $this->ensureDirectory(dirname($target));

        $partsDir = $this->partsDirectory($actor, $uploadId, $fileKey);
        $accumulator = $partsDir.DIRECTORY_SEPARATOR.self::ACCUMULATOR;

        if (! is_file($accumulator)) {
            // A concurrent duplicate of the last slice may already have committed it.
            $completed = $this->completedTarget($actor, $uploadId, $fileKey, $relativePath);

            if ($completed !== null) {
                return $completed;
            }

            throw new OcrServiceException(
                "The reassembled '{$relativePath}' has gone missing. Retry the upload."
            );
        }

        try {
            $target = $this->finalizeAssembly(
                $actor,
                $uploadId,
                $fileKey,
                $relativePath,
                $accumulator,
                $target,
            );
        } finally {
            // Removes the accumulator on success (it was renamed away) and every
            // trace of a failed attempt otherwise.
            $this->deleteDirectory($partsDir);
        }

        return $target;
    }

    /**
     * Commit a fully assembled temporary file and then record which browser file
     * owns its relative path. The short lock prevents two parallel files from both
     * claiming the same path while keeping their large streaming writes concurrent.
     */
    private function finalizeAssembly(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $relativePath,
        string $temporary,
        string $target,
    ): string {
        $lockPath = $this->uploadDirectory($actor, $uploadId).DIRECTORY_SEPARATOR.'.completion.lock';
        $lock = @fopen($lockPath, 'c');

        if ($lock === false || ! flock($lock, LOCK_EX)) {
            if (is_resource($lock)) {
                fclose($lock);
            }

            throw new OcrServiceException('Could not lock the upload for completion.');
        }

        try {
            $completed = $this->completedTarget($actor, $uploadId, $fileKey, $relativePath);
            if ($completed !== null) {
                @unlink($temporary);

                return $completed;
            }

            $backup = null;
            if (is_file($target)) {
                // A target without a marker is legacy/crash residue. Keep it intact
                // until the replacement has been completely assembled.
                $backup = $target.'.ocr-replaced-'.$fileKey.'.bak';
                @unlink($backup);

                if (! @rename($target, $backup)) {
                    throw new OcrServiceException("Could not replace stale upload '{$relativePath}'.");
                }
            }

            if (! @rename($temporary, $target)) {
                if ($backup !== null) {
                    @rename($backup, $target);
                }

                throw new OcrServiceException("Could not finish upload '{$relativePath}'.");
            }

            if ($backup !== null) {
                @unlink($backup);
            }

            // The marker is deliberately last: it must never claim a partial target.
            $this->writeCompletionMarker($actor, $uploadId, $fileKey, $relativePath);

            return $target;
        } finally {
            flock($lock, LOCK_UN);
            fclose($lock);
        }
    }

    /**
     * Return an idempotently completed target, reject a second browser file that
     * claims the same relative path, or return null for an unmarked legacy target.
     */
    private function completedTarget(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $relativePath,
    ): ?string {
        $directory = $this->completionDirectory($actor, $uploadId);
        if (! is_dir($directory)) {
            return null;
        }

        $completed = null;

        foreach (glob($directory.DIRECTORY_SEPARATOR.'*.json') ?: [] as $marker) {
            $markerKey = pathinfo($marker, PATHINFO_FILENAME);
            $data = json_decode((string) @file_get_contents($marker), true);
            $claimedPath = is_array($data) ? ($data['relative_path'] ?? null) : null;

            if ($markerKey === $fileKey && $claimedPath !== $relativePath) {
                throw ValidationException::withMessages([
                    'file_key' => 'The file key has already completed a different upload path.',
                ]);
            }

            if ($claimedPath !== $relativePath) {
                continue;
            }

            if ($markerKey !== $fileKey) {
                throw ValidationException::withMessages([
                    'relative_path' => "The upload contains more than one file at '{$relativePath}'.",
                ]);
            }

            $target = $this->filesDirectory($actor, $uploadId)
                .DIRECTORY_SEPARATOR.str_replace('/', DIRECTORY_SEPARATOR, $relativePath);

            if (is_file($target)) {
                $completed = $target;
            } else {
                // A marker without its target cannot represent a completed upload.
                @unlink($marker);
            }
        }

        return $completed;
    }

    private function writeCompletionMarker(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $relativePath,
    ): void {
        $directory = $this->completionDirectory($actor, $uploadId);
        $this->ensureDirectory($directory);

        $marker = $directory.DIRECTORY_SEPARATOR.$fileKey.'.json';
        $temporary = $marker.'.tmp';
        $json = json_encode(['relative_path' => $relativePath], JSON_UNESCAPED_SLASHES);

        if ($json === false || file_put_contents($temporary, $json, LOCK_EX) === false) {
            @unlink($temporary);
            throw new OcrServiceException('Could not record upload completion.');
        }

        @unlink($marker);
        if (! @rename($temporary, $marker)) {
            @unlink($temporary);
            throw new OcrServiceException('Could not record upload completion.');
        }
    }

    /**
     * Every file assembled under this upload id, recursively.
     *
     * @return list<array{name: string, relative_path: string, path: string, size: int}>
     */
    public function assembledFiles(User $actor, string $uploadId): array
    {
        $dir = $this->filesDirectory($actor, $this->safeId($uploadId, 'upload_id'));

        if (! is_dir($dir)) {
            return [];
        }

        $files = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS)
        );

        foreach ($iterator as $file) {
            if (! $file->isFile() || $file->isLink()) {
                continue;
            }

            $path = $file->getPathname();
            $relativePath = str_replace(
                DIRECTORY_SEPARATOR,
                '/',
                substr($path, strlen($dir) + 1),
            );

            $files[] = [
                'name' => $file->getBasename(),
                'relative_path' => $relativePath,
                'path' => $path,
                'size' => $file->getSize(),
            ];
        }

        usort(
            $files,
            fn (array $left, array $right) => strcmp($left['relative_path'], $right['relative_path'])
        );

        return $files;
    }

    /**
     * Exactly one assembled file, for the surfaces that expect a single archive.
     *
     * @return array{name: string, relative_path: string, path: string, size: int}
     */
    public function singleFile(User $actor, string $uploadId): array
    {
        $files = $this->assembledFiles($actor, $uploadId);

        if ($files === []) {
            throw ValidationException::withMessages([
                'upload_id' => 'No completed upload was found. Try uploading the file again.',
            ]);
        }

        return $files[0];
    }

    /**
     * Remove an upload's working directory. Always call this once the files have
     * been handed to the service, successfully or not.
     */
    public function discard(User $actor, string $uploadId): void
    {
        $this->deleteDirectory($this->uploadDirectory($actor, $this->safeId($uploadId, 'upload_id')));
    }

    /**
     * Sweep uploads abandoned mid-flight. Called opportunistically, since a
     * half-uploaded 100 GB dataset would otherwise sit in storage indefinitely.
     *
     * Uses a directory iterator rather than glob() so the scan does not load
     * every entry into memory at once — a concern when users/ holds many stale
     * upload directories from large datasets.
     */
    public function prune(): int
    {
        $root = $this->root();

        if (! is_dir($root)) {
            return 0;
        }

        $cutoff = now()->subHours(self::STALE_HOURS)->getTimestamp();
        $removed = 0;

        // Two levels deep: <user id>/<upload id>
        foreach (new \DirectoryIterator($root) as $user) {
            if ($user->isDot() || ! $user->isDir()) {
                continue;
            }

            foreach (new \DirectoryIterator($user->getPathname()) as $upload) {
                if ($upload->isDot() || ! $upload->isDir()) {
                    continue;
                }

                if ($upload->getMTime() < $cutoff) {
                    $this->deleteDirectory($upload->getPathname());
                    $removed++;
                }
            }
        }

        return $removed;
    }

    // -------------------------------------------------------------------- validation

    /**
     * The largest slice this server will actually accept, for the browser to size its
     * requests by.
     *
     * The browser used to hardcode 16 MB against a remembered php.ini. That is a
     * guess in both directions: it wastes requests where the limit is higher, and
     * every slice fails with a 413 where it is lower. PHP knows the real numbers, so
     * they are read here and handed to the page.
     */
    public function chunkBytes(): int
    {
        $limits = array_filter([
            $this->iniBytes('upload_max_filesize'),
            $this->iniBytes('post_max_size'),
        ], fn (?int $bytes) => $bytes !== null && $bytes > 0);

        $usable = ($limits === [] ? self::MAX_CHUNK_BYTES + self::MULTIPART_HEADROOM : min($limits))
            - self::MULTIPART_HEADROOM;

        // Whole megabytes: a round slice count is easier to reason about in a log.
        $bytes = intdiv(max($usable, 0), self::MIN_CHUNK_BYTES) * self::MIN_CHUNK_BYTES;

        return max(min($bytes, self::MAX_CHUNK_BYTES), self::MIN_CHUNK_BYTES);
    }

    /**
     * Resolve a php.ini shorthand size ('40M', '1G', '512K') to bytes. Null when the
     * directive is absent; a non-positive value means no limit is imposed.
     */
    private function iniBytes(string $directive): ?int
    {
        $raw = trim((string) ini_get($directive));

        if ($raw === '') {
            return null;
        }

        $value = (int) $raw;
        $unit = strtolower(substr($raw, -1));

        return match ($unit) {
            'g' => $value * 1024 * 1024 * 1024,
            'm' => $value * 1024 * 1024,
            'k' => $value * 1024,
            default => $value,
        };
    }

    private function safeId(string $value, string $field): string
    {
        if (preg_match(self::ID_PATTERN, $value) !== 1) {
            throw ValidationException::withMessages([
                $field => 'Malformed upload identifier.',
            ]);
        }

        return $value;
    }

    /**
     * Keep legacy callers flat-compatible: their bare name is sanitised exactly as
     * before. New relative_path callers use safeRelativePath(), which preserves
     * spelling instead of silently renaming directory-drop files.
     */
    private function safeFilename(string $filename): string
    {
        $name = basename(str_replace('\\', '/', $filename));
        $name = preg_replace('/[^A-Za-z0-9._-]+/', '-', $name) ?? '';
        $name = trim($name, '.-');

        if ($name === '') {
            throw ValidationException::withMessages(['filename' => 'Invalid file name.']);
        }

        $this->assertAllowedExtension($name, 'filename');

        return $name;
    }

    /**
     * Normalise separators while rejecting any path that could escape or alias a
     * target. Safe segment spelling (including spaces and Unicode) is retained.
     */
    private function safeRelativePath(string $relativePath, string $filename): string
    {
        if (
            $relativePath === ''
            || preg_match('/^[\\\\\/]/', $relativePath) === 1
            || preg_match('/^[A-Za-z]:/', $relativePath) === 1
        ) {
            throw ValidationException::withMessages([
                'relative_path' => 'The file path must be relative to the selected folder.',
            ]);
        }

        $path = str_replace('\\', '/', $relativePath);
        $segments = explode('/', $path);

        foreach ($segments as $segment) {
            if ($segment === '' || $segment === '.' || $segment === '..') {
                throw ValidationException::withMessages([
                    'relative_path' => 'The file path contains an empty or traversal segment.',
                ]);
            }

            if (
                strlen($segment) > 255
                || preg_match('/[\x00-\x1F\x7F]/', $segment) === 1
                || preg_match('/[<>:"|?*]/', $segment) === 1
                || rtrim($segment, ' .') !== $segment
            ) {
                throw ValidationException::withMessages([
                    'relative_path' => 'The file path contains characters that are unsafe on the server.',
                ]);
            }

            $stem = pathinfo($segment, PATHINFO_FILENAME);
            if (preg_match('/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$/i', $stem) === 1) {
                throw ValidationException::withMessages([
                    'relative_path' => 'The file path contains a reserved file name.',
                ]);
            }
        }

        $originalName = str_replace('\\', '/', $filename);
        if (str_contains($originalName, '/') || basename($path) !== $originalName) {
            throw ValidationException::withMessages([
                'relative_path' => 'The file name does not match the relative path.',
            ]);
        }

        $this->assertAllowedExtension(basename($path), 'relative_path');

        return implode('/', $segments);
    }

    private function assertAllowedExtension(string $name, string $field): void
    {
        $extension = strtolower(pathinfo($name, PATHINFO_EXTENSION));

        if (! in_array($extension, self::ALLOWED_EXTENSIONS, true)) {
            throw ValidationException::withMessages([
                $field => "Files of type '.{$extension}' are not accepted.",
            ]);
        }
    }

    // ----------------------------------------------------------------------- paths

    private function root(): string
    {
        return storage_path('app/ocr-uploads');
    }

    private function uploadDirectory(User $actor, string $uploadId): string
    {
        return $this->root()
            .DIRECTORY_SEPARATOR.$actor->getKey()
            .DIRECTORY_SEPARATOR.$uploadId;
    }

    private function partsDirectory(User $actor, string $uploadId, string $fileKey): string
    {
        return $this->uploadDirectory($actor, $uploadId)
            .DIRECTORY_SEPARATOR.'parts'
            .DIRECTORY_SEPARATOR.$fileKey;
    }

    private function filesDirectory(User $actor, string $uploadId): string
    {
        return $this->uploadDirectory($actor, $uploadId).DIRECTORY_SEPARATOR.'files';
    }

    private function completionDirectory(User $actor, string $uploadId): string
    {
        return $this->uploadDirectory($actor, $uploadId).DIRECTORY_SEPARATOR.'completed';
    }

    private function ensureDirectory(string $path): void
    {
        if (! is_dir($path) && ! mkdir($path, 0o755, true) && ! is_dir($path)) {
            throw new OcrServiceException('Could not create the upload directory.');
        }
    }

    private function deleteDirectory(string $path): void
    {
        if (! is_dir($path)) {
            return;
        }

        foreach (scandir($path) ?: [] as $entry) {
            if (in_array($entry, ['.', '..'], true)) {
                continue;
            }

            $child = $path.DIRECTORY_SEPARATOR.$entry;
            is_dir($child) ? $this->deleteDirectory($child) : @unlink($child);
        }

        @rmdir($path);
    }
}
