<?php

namespace App\Services\Ocr;

use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Validation\ValidationException;

/**
 * Reassembles browser-sliced uploads.
 *
 * PHP's `upload_max_filesize` is 40M here, but model weights are around 1.3 GB and
 * a dataset can be thousands of images. A plain multipart post is rejected by PHP
 * before Laravel ever sees it, so chunked upload is a requirement rather than an
 * optimisation: the browser slices each file, posts the pieces, and this class
 * stitches them back together before the result is handed to the OCR service.
 *
 * Layout under storage/app/ocr-uploads/:
 *
 *     <user id>/<upload id>/parts/<file key>/<index>.part   in-flight slices
 *     <user id>/<upload id>/files/<relative path>            assembled files
 *     <user id>/<upload id>/completed/<file key>.json        completion marker
 *
 * Namespacing by user id is deliberate: an upload id is generated by the browser,
 * so one account must not be able to guess another's and claim its files.
 */
class ChunkedUpload
{
    /** Ids are browser-generated, so they are validated rather than trusted. */
    private const ID_PATTERN = '/^[A-Za-z0-9]{8,64}$/';

    /** A 1.3 GB file at 5 MB a slice is ~270 chunks. 100 GB at 16 MB is ~6 400
     *  chunks. This gives generous headroom for either. */
    private const MAX_CHUNKS = 10_000;

    /** Abandoned uploads are swept after this long. */
    private const STALE_HOURS = 24;

    /**
     * Extensions accepted in any assembled file. The OCR service applies its own
     * whitelist too - this is the outer of two gates, not the only one.
     */
    private const ALLOWED_EXTENSIONS = [
        // Model folders
        'json', 'safetensors', 'bin', 'txt', 'model',
        // Datasets
        'zip', 'csv',
        // Predict images
        'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff',
    ];

    /**
     * Store one slice. When the last one arrives, assemble the file.
     *
     * @return array{complete: bool, received: int, total: int, name: string, relative_path: string, path: string|null}
     */
    public function receive(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $filename,
        int $index,
        int $total,
        UploadedFile $chunk,
        ?string $relativePath = null,
    ): array {
        $uploadId = $this->safeId($uploadId, 'upload_id');
        $fileKey = $this->safeId($fileKey, 'file_key');
        $relativePath = $relativePath === null
            ? $this->safeFilename($filename)
            : $this->safeRelativePath($relativePath, $filename);
        $name = basename($relativePath);

        if ($total < 1 || $total > self::MAX_CHUNKS) {
            throw ValidationException::withMessages([
                'total' => 'Chunk count must be between 1 and '.self::MAX_CHUNKS.'.',
            ]);
        }

        if ($index < 0 || $index >= $total) {
            throw ValidationException::withMessages([
                'index' => 'Chunk index is outside the declared range.',
            ]);
        }

        $completed = $this->completedTarget($actor, $uploadId, $fileKey, $relativePath);
        if ($completed !== null && $index === $total - 1) {
            $this->deleteDirectory($this->partsDirectory($actor, $uploadId, $fileKey));

            return [
                'complete' => true,
                'received' => $total,
                'total' => $total,
                'name' => $name,
                'relative_path' => $relativePath,
                'path' => $completed,
            ];
        }

        $partsDir = $this->partsDirectory($actor, $uploadId, $fileKey);
        $this->ensureDirectory($partsDir);

        // move() rather than a copy: the slice is already a temp file on disk.
        $chunk->move($partsDir, $index.'.part');

        $received = count(glob($partsDir.DIRECTORY_SEPARATOR.'*.part') ?: []);

        if ($received < $total) {
            return [
                'complete' => false,
                'received' => $received,
                'total' => $total,
                'name' => $name,
                'relative_path' => $relativePath,
                'path' => null,
            ];
        }

        return [
            'complete' => true,
            'received' => $received,
            'total' => $total,
            'name' => $name,
            'relative_path' => $relativePath,
            'path' => $this->assemble(
                $actor,
                $uploadId,
                $fileKey,
                $relativePath,
                $total,
            ),
        ];
    }

    /**
     * Concatenate the slices in order, then drop them.
     *
     * Streamed a slice at a time: reading a 1.3 GB file into a string would exhaust
     * PHP's memory limit long before the write.
     */
    private function assemble(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $relativePath,
        int $total,
    ): string {
        $filesDir = $this->filesDirectory($actor, $uploadId);
        $target = $filesDir.DIRECTORY_SEPARATOR.str_replace('/', DIRECTORY_SEPARATOR, $relativePath);
        $targetDir = dirname($target);
        $this->ensureDirectory($targetDir);

        $partsDir = $this->partsDirectory($actor, $uploadId, $fileKey);
        $name = basename($relativePath);
        $temporary = $targetDir.DIRECTORY_SEPARATOR.'.ocr-upload-'.$fileKey.'.tmp';
        $out = @fopen($temporary, 'wb');

        if ($out === false) {
            throw new OcrServiceException("Could not open '{$relativePath}' for writing.");
        }

        try {
            for ($i = 0; $i < $total; $i++) {
                $part = $partsDir.DIRECTORY_SEPARATOR.$i.'.part';

                if (! is_file($part)) {
                    throw new OcrServiceException(
                        "Chunk {$i} of '{$name}' is missing. Retry the upload."
                    );
                }

                $in = @fopen($part, 'rb');
                if ($in === false || stream_copy_to_stream($in, $out) === false) {
                    if (is_resource($in)) {
                        fclose($in);
                    }

                    throw new OcrServiceException("Could not assemble '{$relativePath}'.");
                }
                fclose($in);
            }

            fclose($out);
            $out = null;

            $target = $this->finalizeAssembly(
                $actor,
                $uploadId,
                $fileKey,
                $relativePath,
                $temporary,
                $target,
            );
        } catch (\Throwable $e) {
            if (is_resource($out)) {
                fclose($out);
            }
            @unlink($temporary);
            $this->deleteDirectory($partsDir);

            throw $e;
        }

        $this->deleteDirectory($partsDir);

        return $target;
    }

    /**
     * Commit a fully assembled temporary file and then record which browser file
     * owns its relative path. The short lock prevents two parallel files from both
     * claiming the same path while keeping their large streaming writes concurrent.
     */
    private function finalizeAssembly(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $relativePath,
        string $temporary,
        string $target,
    ): string {
        $lockPath = $this->uploadDirectory($actor, $uploadId).DIRECTORY_SEPARATOR.'.completion.lock';
        $lock = @fopen($lockPath, 'c');

        if ($lock === false || ! flock($lock, LOCK_EX)) {
            if (is_resource($lock)) {
                fclose($lock);
            }

            throw new OcrServiceException('Could not lock the upload for completion.');
        }

        try {
            $completed = $this->completedTarget($actor, $uploadId, $fileKey, $relativePath);
            if ($completed !== null) {
                @unlink($temporary);

                return $completed;
            }

            $backup = null;
            if (is_file($target)) {
                // A target without a marker is legacy/crash residue. Keep it intact
                // until the replacement has been completely assembled.
                $backup = $target.'.ocr-replaced-'.$fileKey.'.bak';
                @unlink($backup);

                if (! @rename($target, $backup)) {
                    throw new OcrServiceException("Could not replace stale upload '{$relativePath}'.");
                }
            }

            if (! @rename($temporary, $target)) {
                if ($backup !== null) {
                    @rename($backup, $target);
                }

                throw new OcrServiceException("Could not finish upload '{$relativePath}'.");
            }

            if ($backup !== null) {
                @unlink($backup);
            }

            // The marker is deliberately last: it must never claim a partial target.
            $this->writeCompletionMarker($actor, $uploadId, $fileKey, $relativePath);

            return $target;
        } finally {
            flock($lock, LOCK_UN);
            fclose($lock);
        }
    }

    /**
     * Return an idempotently completed target, reject a second browser file that
     * claims the same relative path, or return null for an unmarked legacy target.
     */
    private function completedTarget(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $relativePath,
    ): ?string {
        $directory = $this->completionDirectory($actor, $uploadId);
        if (! is_dir($directory)) {
            return null;
        }

        $completed = null;

        foreach (glob($directory.DIRECTORY_SEPARATOR.'*.json') ?: [] as $marker) {
            $markerKey = pathinfo($marker, PATHINFO_FILENAME);
            $data = json_decode((string) @file_get_contents($marker), true);
            $claimedPath = is_array($data) ? ($data['relative_path'] ?? null) : null;

            if ($markerKey === $fileKey && $claimedPath !== $relativePath) {
                throw ValidationException::withMessages([
                    'file_key' => 'The file key has already completed a different upload path.',
                ]);
            }

            if ($claimedPath !== $relativePath) {
                continue;
            }

            if ($markerKey !== $fileKey) {
                throw ValidationException::withMessages([
                    'relative_path' => "The upload contains more than one file at '{$relativePath}'.",
                ]);
            }

            $target = $this->filesDirectory($actor, $uploadId)
                .DIRECTORY_SEPARATOR.str_replace('/', DIRECTORY_SEPARATOR, $relativePath);

            if (is_file($target)) {
                $completed = $target;
            } else {
                // A marker without its target cannot represent a completed upload.
                @unlink($marker);
            }
        }

        return $completed;
    }

    private function writeCompletionMarker(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $relativePath,
    ): void {
        $directory = $this->completionDirectory($actor, $uploadId);
        $this->ensureDirectory($directory);

        $marker = $directory.DIRECTORY_SEPARATOR.$fileKey.'.json';
        $temporary = $marker.'.tmp';
        $json = json_encode(['relative_path' => $relativePath], JSON_UNESCAPED_SLASHES);

        if ($json === false || file_put_contents($temporary, $json, LOCK_EX) === false) {
            @unlink($temporary);
            throw new OcrServiceException('Could not record upload completion.');
        }

        @unlink($marker);
        if (! @rename($temporary, $marker)) {
            @unlink($temporary);
            throw new OcrServiceException('Could not record upload completion.');
        }
    }

    /**
     * Every file assembled under this upload id, recursively.
     *
     * @return list<array{name: string, relative_path: string, path: string, size: int}>
     */
    public function assembledFiles(User $actor, string $uploadId): array
    {
        $dir = $this->filesDirectory($actor, $this->safeId($uploadId, 'upload_id'));

        if (! is_dir($dir)) {
            return [];
        }

        $files = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS)
        );

        foreach ($iterator as $file) {
            if (! $file->isFile() || $file->isLink()) {
                continue;
            }

            $path = $file->getPathname();
            $relativePath = str_replace(
                DIRECTORY_SEPARATOR,
                '/',
                substr($path, strlen($dir) + 1),
            );

            $files[] = [
                'name' => $file->getBasename(),
                'relative_path' => $relativePath,
                'path' => $path,
                'size' => $file->getSize(),
            ];
        }

        usort(
            $files,
            fn (array $left, array $right) => strcmp($left['relative_path'], $right['relative_path'])
        );

        return $files;
    }

    /**
     * Exactly one assembled file, for the surfaces that expect a single archive.
     *
     * @return array{name: string, relative_path: string, path: string, size: int}
     */
    public function singleFile(User $actor, string $uploadId): array
    {
        $files = $this->assembledFiles($actor, $uploadId);

        if ($files === []) {
            throw ValidationException::withMessages([
                'upload_id' => 'No completed upload was found. Try uploading the file again.',
            ]);
        }

        return $files[0];
    }

    /**
     * Remove an upload's working directory. Always call this once the files have
     * been handed to the service, successfully or not.
     */
    public function discard(User $actor, string $uploadId): void
    {
        $this->deleteDirectory($this->uploadDirectory($actor, $this->safeId($uploadId, 'upload_id')));
    }

    /**
     * Sweep uploads abandoned mid-flight. Called opportunistically, since a
     * half-uploaded 100 GB dataset would otherwise sit in storage indefinitely.
     *
     * Uses a directory iterator rather than glob() so the scan does not load
     * every entry into memory at once — a concern when users/ holds many stale
     * upload directories from large datasets.
     */
    public function prune(): int
    {
        $root = $this->root();

        if (! is_dir($root)) {
            return 0;
        }

        $cutoff = now()->subHours(self::STALE_HOURS)->getTimestamp();
        $removed = 0;

        // Two levels deep: <user id>/<upload id>
        foreach (new \DirectoryIterator($root) as $user) {
            if ($user->isDot() || ! $user->isDir()) {
                continue;
            }

            foreach (new \DirectoryIterator($user->getPathname()) as $upload) {
                if ($upload->isDot() || ! $upload->isDir()) {
                    continue;
                }

                if ($upload->getMTime() < $cutoff) {
                    $this->deleteDirectory($upload->getPathname());
                    $removed++;
                }
            }
        }

        return $removed;
    }

    // -------------------------------------------------------------------- validation

    private function safeId(string $value, string $field): string
    {
        if (preg_match(self::ID_PATTERN, $value) !== 1) {
            throw ValidationException::withMessages([
                $field => 'Malformed upload identifier.',
            ]);
        }

        return $value;
    }

    /**
     * Keep legacy callers flat-compatible: their bare name is sanitised exactly as
     * before. New relative_path callers use safeRelativePath(), which preserves
     * spelling instead of silently renaming directory-drop files.
     */
    private function safeFilename(string $filename): string
    {
        $name = basename(str_replace('\\', '/', $filename));
        $name = preg_replace('/[^A-Za-z0-9._-]+/', '-', $name) ?? '';
        $name = trim($name, '.-');

        if ($name === '') {
            throw ValidationException::withMessages(['filename' => 'Invalid file name.']);
        }

        $this->assertAllowedExtension($name, 'filename');

        return $name;
    }

    /**
     * Normalise separators while rejecting any path that could escape or alias a
     * target. Safe segment spelling (including spaces and Unicode) is retained.
     */
    private function safeRelativePath(string $relativePath, string $filename): string
    {
        if (
            $relativePath === ''
            || preg_match('/^[\\\\\/]/', $relativePath) === 1
            || preg_match('/^[A-Za-z]:/', $relativePath) === 1
        ) {
            throw ValidationException::withMessages([
                'relative_path' => 'The file path must be relative to the selected folder.',
            ]);
        }

        $path = str_replace('\\', '/', $relativePath);
        $segments = explode('/', $path);

        foreach ($segments as $segment) {
            if ($segment === '' || $segment === '.' || $segment === '..') {
                throw ValidationException::withMessages([
                    'relative_path' => 'The file path contains an empty or traversal segment.',
                ]);
            }

            if (
                strlen($segment) > 255
                || preg_match('/[\x00-\x1F\x7F]/', $segment) === 1
                || preg_match('/[<>:"|?*]/', $segment) === 1
                || rtrim($segment, ' .') !== $segment
            ) {
                throw ValidationException::withMessages([
                    'relative_path' => 'The file path contains characters that are unsafe on the server.',
                ]);
            }

            $stem = pathinfo($segment, PATHINFO_FILENAME);
            if (preg_match('/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$/i', $stem) === 1) {
                throw ValidationException::withMessages([
                    'relative_path' => 'The file path contains a reserved file name.',
                ]);
            }
        }

        $originalName = str_replace('\\', '/', $filename);
        if (str_contains($originalName, '/') || basename($path) !== $originalName) {
            throw ValidationException::withMessages([
                'relative_path' => 'The file name does not match the relative path.',
            ]);
        }

        $this->assertAllowedExtension(basename($path), 'relative_path');

        return implode('/', $segments);
    }

    private function assertAllowedExtension(string $name, string $field): void
    {
        $extension = strtolower(pathinfo($name, PATHINFO_EXTENSION));

        if (! in_array($extension, self::ALLOWED_EXTENSIONS, true)) {
            throw ValidationException::withMessages([
                $field => "Files of type '.{$extension}' are not accepted.",
            ]);
        }
    }

    // ----------------------------------------------------------------------- paths

    private function root(): string
    {
        return storage_path('app/ocr-uploads');
    }

    private function uploadDirectory(User $actor, string $uploadId): string
    {
        return $this->root()
            .DIRECTORY_SEPARATOR.$actor->getKey()
            .DIRECTORY_SEPARATOR.$uploadId;
    }

    private function partsDirectory(User $actor, string $uploadId, string $fileKey): string
    {
        return $this->uploadDirectory($actor, $uploadId)
            .DIRECTORY_SEPARATOR.'parts'
            .DIRECTORY_SEPARATOR.$fileKey;
    }

    private function filesDirectory(User $actor, string $uploadId): string
    {
        return $this->uploadDirectory($actor, $uploadId).DIRECTORY_SEPARATOR.'files';
    }

    private function completionDirectory(User $actor, string $uploadId): string
    {
        return $this->uploadDirectory($actor, $uploadId).DIRECTORY_SEPARATOR.'completed';
    }

    private function ensureDirectory(string $path): void
    {
        if (! is_dir($path) && ! mkdir($path, 0o755, true) && ! is_dir($path)) {
            throw new OcrServiceException('Could not create the upload directory.');
        }
    }

    private function deleteDirectory(string $path): void
    {
        if (! is_dir($path)) {
            return;
        }

        foreach (scandir($path) ?: [] as $entry) {
            if (in_array($entry, ['.', '..'], true)) {
                continue;
            }

            $child = $path.DIRECTORY_SEPARATOR.$entry;
            is_dir($child) ? $this->deleteDirectory($child) : @unlink($child);
        }

        @rmdir($path);
    }
}
