<?php

namespace App\Services\Ocr;

use App\Models\User;
use Illuminate\Http\UploadedFile;
use Illuminate\Validation\ValidationException;

/**
 * Reassembles browser-sliced uploads.
 *
 * PHP's `upload_max_filesize` is 40M here, but model weights are around 1.3 GB and
 * a dataset can be thousands of images. A plain multipart post is rejected by PHP
 * before Laravel ever sees it, so chunked upload is a requirement rather than an
 * optimisation: the browser slices each file, posts the pieces, and this class
 * stitches them back together before the result is handed to the OCR service.
 *
 * Layout under storage/app/ocr-uploads/:
 *
 *     <user id>/<upload id>/parts/<file key>/<index>.part   in-flight slices
 *     <user id>/<upload id>/files/<filename>                assembled files
 *
 * Namespacing by user id is deliberate: an upload id is generated by the browser,
 * so one account must not be able to guess another's and claim its files.
 */
class ChunkedUpload
{
    /** Ids are browser-generated, so they are validated rather than trusted. */
    private const ID_PATTERN = '/^[A-Za-z0-9]{8,64}$/';

    /** A 1.3 GB file at 5 MB a slice is ~270 chunks; this is generous headroom. */
    private const MAX_CHUNKS = 20_000;

    /** Abandoned uploads are swept after this long. */
    private const STALE_HOURS = 24;

    /**
     * Extensions accepted in any assembled file. The OCR service applies its own
     * whitelist too - this is the outer of two gates, not the only one.
     */
    private const ALLOWED_EXTENSIONS = [
        // Model folders
        'json', 'safetensors', 'bin', 'txt', 'model',
        // Datasets
        'zip',
        // Predict images
        'png', 'jpg', 'jpeg', 'bmp', 'tif', 'tiff',
    ];

    /**
     * Store one slice. When the last one arrives, assemble the file.
     *
     * @return array{complete: bool, received: int, total: int, name: string, path: string|null}
     */
    public function receive(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $filename,
        int $index,
        int $total,
        UploadedFile $chunk,
    ): array {
        $uploadId = $this->safeId($uploadId, 'upload_id');
        $fileKey = $this->safeId($fileKey, 'file_key');
        $name = $this->safeFilename($filename);

        if ($total < 1 || $total > self::MAX_CHUNKS) {
            throw ValidationException::withMessages([
                'total' => "Chunk count must be between 1 and ".self::MAX_CHUNKS.'.',
            ]);
        }

        if ($index < 0 || $index >= $total) {
            throw ValidationException::withMessages([
                'index' => 'Chunk index is outside the declared range.',
            ]);
        }

        $partsDir = $this->partsDirectory($actor, $uploadId, $fileKey);
        $this->ensureDirectory($partsDir);

        // move() rather than a copy: the slice is already a temp file on disk.
        $chunk->move($partsDir, $index.'.part');

        $received = count(glob($partsDir.DIRECTORY_SEPARATOR.'*.part') ?: []);

        if ($received < $total) {
            return [
                'complete' => false,
                'received' => $received,
                'total' => $total,
                'name' => $name,
                'path' => null,
            ];
        }

        return [
            'complete' => true,
            'received' => $received,
            'total' => $total,
            'name' => $name,
            'path' => $this->assemble($actor, $uploadId, $fileKey, $name, $total),
        ];
    }

    /**
     * Concatenate the slices in order, then drop them.
     *
     * Streamed a slice at a time: reading a 1.3 GB file into a string would exhaust
     * PHP's memory limit long before the write.
     */
    private function assemble(
        User $actor,
        string $uploadId,
        string $fileKey,
        string $name,
        int $total,
    ): string {
        $filesDir = $this->filesDirectory($actor, $uploadId);
        $this->ensureDirectory($filesDir);

        $partsDir = $this->partsDirectory($actor, $uploadId, $fileKey);
        $target = $filesDir.DIRECTORY_SEPARATOR.$name;

        $out = fopen($target, 'wb');

        if ($out === false) {
            throw new OcrServiceException("Could not open '{$name}' for writing.");
        }

        try {
            for ($i = 0; $i < $total; $i++) {
                $part = $partsDir.DIRECTORY_SEPARATOR.$i.'.part';

                if (! is_file($part)) {
                    throw new OcrServiceException(
                        "Chunk {$i} of '{$name}' is missing. Retry the upload."
                    );
                }

                $in = fopen($part, 'rb');
                stream_copy_to_stream($in, $out);
                fclose($in);
            }
        } catch (\Throwable $e) {
            fclose($out);
            @unlink($target);      // never leave a truncated file behind
            $this->deleteDirectory($partsDir);

            throw $e;
        }

        fclose($out);
        $this->deleteDirectory($partsDir);

        return $target;
    }

    /**
     * Every file assembled under this upload id.
     *
     * @return list<array{name: string, path: string, size: int}>
     */
    public function assembledFiles(User $actor, string $uploadId): array
    {
        $dir = $this->filesDirectory($actor, $this->safeId($uploadId, 'upload_id'));

        if (! is_dir($dir)) {
            return [];
        }

        return collect(scandir($dir) ?: [])
            ->reject(fn (string $entry) => in_array($entry, ['.', '..'], true))
            ->map(fn (string $entry) => $dir.DIRECTORY_SEPARATOR.$entry)
            ->filter(fn (string $path) => is_file($path))
            ->map(fn (string $path) => [
                'name' => basename($path),
                'path' => $path,
                'size' => filesize($path) ?: 0,
            ])
            ->sortBy('name')
            ->values()
            ->all();
    }

    /**
     * Exactly one assembled file, for the surfaces that expect a single archive.
     *
     * @return array{name: string, path: string, size: int}
     */
    public function singleFile(User $actor, string $uploadId): array
    {
        $files = $this->assembledFiles($actor, $uploadId);

        if ($files === []) {
            throw ValidationException::withMessages([
                'upload_id' => 'No completed upload was found. Try uploading the file again.',
            ]);
        }

        return $files[0];
    }

    /**
     * Remove an upload's working directory. Always call this once the files have
     * been handed to the service, successfully or not.
     */
    public function discard(User $actor, string $uploadId): void
    {
        $this->deleteDirectory($this->uploadDirectory($actor, $this->safeId($uploadId, 'upload_id')));
    }

    /**
     * Sweep uploads abandoned mid-flight. Called opportunistically, since a
     * half-uploaded 1.3 GB model would otherwise sit on disk indefinitely.
     */
    public function prune(): int
    {
        $root = $this->root();

        if (! is_dir($root)) {
            return 0;
        }

        $cutoff = now()->subHours(self::STALE_HOURS)->getTimestamp();
        $removed = 0;

        foreach (glob($root.DIRECTORY_SEPARATOR.'*'.DIRECTORY_SEPARATOR.'*') ?: [] as $dir) {
            if (is_dir($dir) && filemtime($dir) < $cutoff) {
                $this->deleteDirectory($dir);
                $removed++;
            }
        }

        return $removed;
    }

    // -------------------------------------------------------------------- validation

    private function safeId(string $value, string $field): string
    {
        if (preg_match(self::ID_PATTERN, $value) !== 1) {
            throw ValidationException::withMessages([
                $field => 'Malformed upload identifier.',
            ]);
        }

        return $value;
    }

    /**
     * Reduce to a bare filename and check the extension.
     *
     * Path separators and `..` are stripped rather than rejected quietly: the goal
     * is that no value can ever address a directory other than the upload's own.
     */
    private function safeFilename(string $filename): string
    {
        $name = basename(str_replace('\\', '/', $filename));
        $name = preg_replace('/[^A-Za-z0-9._-]+/', '-', $name) ?? '';
        $name = trim($name, '.-');

        if ($name === '') {
            throw ValidationException::withMessages(['filename' => 'Invalid file name.']);
        }

        $extension = strtolower(pathinfo($name, PATHINFO_EXTENSION));

        if (! in_array($extension, self::ALLOWED_EXTENSIONS, true)) {
            throw ValidationException::withMessages([
                'filename' => "Files of type '.{$extension}' are not accepted.",
            ]);
        }

        return $name;
    }

    // ----------------------------------------------------------------------- paths

    private function root(): string
    {
        return storage_path('app/ocr-uploads');
    }

    private function uploadDirectory(User $actor, string $uploadId): string
    {
        return $this->root()
            .DIRECTORY_SEPARATOR.$actor->getKey()
            .DIRECTORY_SEPARATOR.$uploadId;
    }

    private function partsDirectory(User $actor, string $uploadId, string $fileKey): string
    {
        return $this->uploadDirectory($actor, $uploadId)
            .DIRECTORY_SEPARATOR.'parts'
            .DIRECTORY_SEPARATOR.$fileKey;
    }

    private function filesDirectory(User $actor, string $uploadId): string
    {
        return $this->uploadDirectory($actor, $uploadId).DIRECTORY_SEPARATOR.'files';
    }

    private function ensureDirectory(string $path): void
    {
        if (! is_dir($path) && ! mkdir($path, 0o755, true) && ! is_dir($path)) {
            throw new OcrServiceException('Could not create the upload directory.');
        }
    }

    private function deleteDirectory(string $path): void
    {
        if (! is_dir($path)) {
            return;
        }

        foreach (scandir($path) ?: [] as $entry) {
            if (in_array($entry, ['.', '..'], true)) {
                continue;
            }

            $child = $path.DIRECTORY_SEPARATOR.$entry;
            is_dir($child) ? $this->deleteDirectory($child) : @unlink($child);
        }

        @rmdir($path);
    }
}
